import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import { PNG } from 'pngjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('test-results',{recursive:true});
const settle=()=>page.evaluate(()=>new Promise(done=>requestAnimationFrame(()=>requestAnimationFrame(done))));
async function checkPixels(selector,path){
  const buffer=await page.locator(selector).screenshot({path});
  const png=PNG.sync.read(buffer),colors=new Set();
  for(let i=0;i<png.data.length;i+=16)colors.add(`${png.data[i]},${png.data[i+1]},${png.data[i+2]}`);
  assert.ok(png.width>80&&png.height>80&&colors.size>30,`${selector}: lienzo vacio o demasiado pequeno`);
  return buffer;
}
try{
  await page.goto(process.env.APP_URL||'http://127.0.0.1:3015',{waitUntil:'networkidle',timeout:60000});
  await page.locator('#project-save').waitFor();
  await page.locator('#status-message').waitFor();
  for (const id of ['tool-select','tool-grid','tool-level','tool-zapata','tool-columna','tool-viga','tool-techo','ribbon-level-select','visual-style-select','btn-export-csv-direct','btn-export-json-direct']) {
    await page.locator(`#${id}`).waitFor({state:'attached'});
  }
  assert.ok(await page.locator('#status-metrics').textContent().then(text=>text.includes('Elementos:')));
  assert.ok(await page.locator('#status-coords').textContent().then(text=>text.includes('X:')));
  await page.locator('#sidebar-tab-browser').click();
  await page.waitForFunction(() => document.querySelector('#sidebar-tab-browser')?.getAttribute('aria-selected') === 'true');
  assert.equal(await page.locator('#sidebar-tab-browser').getAttribute('aria-selected'),'true');
  assert.equal(await page.locator('#sidebar-browser').isVisible(),true);
  assert.equal(await page.locator('#sidebar-properties').isVisible(),false);
  await page.locator('#sidebar-tab-properties').click();
  assert.equal(await page.locator('#sidebar-properties').isVisible(),true);
  await page.locator('#ribbon-tab-view').click();
  assert.equal(await page.locator('#ribbon-tab-view').getAttribute('aria-selected'),'true');
  assert.equal(await page.locator('#panel-view').isVisible(),true);
  assert.equal(await page.locator('#panel-view').getAttribute('role'),'tabpanel');
  assert.equal(await page.locator('#panel-view').getAttribute('aria-labelledby'),'ribbon-tab-view');
  await page.locator('#ribbon-tab-view').press('ArrowRight');
  assert.equal(await page.locator('#ribbon-tab-manage').getAttribute('aria-selected'),'true');
  assert.equal(await page.locator('#panel-manage').isVisible(),true);
  await page.locator('#btn-open-mongo-inspector').click();
  await page.locator('#mongo-json-viewer').waitFor();
  assert.equal(await page.locator('#mongo-tab-elements').getAttribute('aria-selected'),'true');
  assert.match(await page.locator('#count-elements').textContent(),/\(\d+\)/);
  await page.locator('#mongo-tab-grids').click();
  assert.equal(await page.locator('#mongo-tab-grids').getAttribute('aria-selected'),'true');
  assert.ok((await page.locator('#mongo-cli-command').textContent()).includes('--collection=grids'));
  await page.locator('#mongo-close').click();
  await page.keyboard.press('Control+Shift+m');
  await page.locator('#mongo-json-viewer').waitFor();
  await page.keyboard.press('Escape');
  await page.locator('#mongo-json-viewer').waitFor({state:'detached'});
  await page.locator('#ribbon-tab-structure').click();
  assert.equal(await page.locator('#panel-structure').isVisible(),true);
  await page.locator('#layout-split-v').click();
  assert.equal(await page.locator('#layout-split-v').getAttribute('aria-pressed'),'true');
  await page.locator('#layout-single').click();
  assert.equal(await page.locator('#viewport-view-3d').getAttribute('role'),'tabpanel');
  assert.equal(await page.locator('#viewport-view-3d').getAttribute('aria-labelledby'),'view-tab-view-3d');
  await page.locator('#tabs-overflow-btn').click();
  assert.equal(await page.locator('#tabs-overflow-btn').getAttribute('aria-expanded'),'true');
  assert.equal(await page.locator('#tabs-overflow-menu').isVisible(),true);
  await page.locator('#overflow-close-others').click();
  assert.equal(await page.locator('#tabs-overflow-menu').isVisible(),false);
  await page.locator('#btn-full-building').click();
  await page.locator('#examples-load').click();
  await settle();
  await page.locator('#sidebar-tab-browser').click();
  const firstPlan = page.locator('#browser-floor-plans-list [data-open-view]').first();
  await firstPlan.waitFor();
  const firstPlanId = await firstPlan.getAttribute('data-open-view');
  await firstPlan.click();
  await page.locator(`#view-tab-${firstPlanId}`).waitFor();
  assert.equal(await page.locator(`#view-tab-${firstPlanId}`).getAttribute('aria-selected'),'true');
  await page.locator('#view-tab-view-3d').click();
  await page.locator('#sidebar-tab-properties').click();
  await settle();
  const before=await checkPixels('#canvas-container canvas','test-results/model-desktop.png');
  const view=await page.locator('.view-panel-content').first().boundingBox();
  await page.mouse.move(view.x+view.width*.65,view.y+view.height*.5);
  await page.mouse.down({button:'right'});
  await page.mouse.move(view.x+view.width*.65+60,view.y+view.height*.5+30,{steps:10});
  await page.mouse.up({button:'right'});await settle();
  const after=await checkPixels('#canvas-container canvas','test-results/model-interaction.png');
  assert.ok(!before.equals(after),'La vista 3D debe responder al desplazamiento');
  await page.mouse.move(view.x+view.width*.65+60,view.y+view.height*.5+30);
  await page.mouse.down({button:'right'});await page.mouse.move(view.x+view.width*.65,view.y+view.height*.5,{steps:10});await page.mouse.up({button:'right'});
  await page.setViewportSize({width:390,height:844});await settle();
  assert.equal(await page.locator('#app-sidebar').isVisible(),false);
  await page.locator('#project-sidebar').click();assert.equal(await page.locator('#app-sidebar').isVisible(),true);
  await page.locator('#project-sidebar').click();assert.equal(await page.locator('#app-sidebar').isVisible(),false);
  await checkPixels('#canvas-container canvas','test-results/model-mobile.png');
  await page.screenshot({path:'test-results/workspace-mobile.png'});
  await page.setViewportSize({width:1440,height:1000});await settle();
  await page.locator('#btn-open-schedule').click();
  await page.locator('#sched-body tr[data-index]').first().waitFor();
  assert.equal(await page.locator('#sched-body tr[data-index]').count(),50);
  await page.screenshot({path:'test-results/schedule-desktop.png'});
  await page.locator('#sched-category').selectOption('OST_Floors');
  const count=await page.locator('#sched-body tr[data-index]').count();assert.ok(count>0);
  const slabLevel=await page.locator('#sched-body tr[data-index]').first().locator('td').nth(4).textContent();
  await page.locator('#sched-level').selectOption({label:slabLevel});
  const filtered=await page.locator('#sched-body tr[data-index]').count();assert.ok(filtered>0&&filtered<=count);
  const exportWait=page.waitForEvent('download');await page.locator('#sched-export').click();await (await exportWait).saveAs('test-results/filtered.csv');
  await page.locator('[data-focus]').first().click();
  await page.locator('#btn-ctx-sketch').click();
  await page.locator('#contour-canvas').waitFor();
  await checkPixels('#contour-canvas','test-results/contour-canvas.png');
  await page.screenshot({path:'test-results/contour-desktop.png'});
  await page.locator('[data-param="thickness"]').fill('0.35');await page.locator('[data-param="thickness"]').press('Tab');
  await page.locator('#contour-cancel').click();
  await page.locator('#btn-ctx-sketch').click();assert.equal(await page.locator('[data-param="thickness"]').inputValue(),'0.2');
  await page.locator('#contour-insert').click();assert.equal(await page.locator('#contour-vertices tr').count(),5);
  await page.locator('#contour-undo').click();assert.equal(await page.locator('#contour-vertices tr').count(),4);
  await page.locator('#contour-hole').click();
  const sketch=await page.locator('#contour-canvas').boundingBox();
  for(const [dx,dy] of [[-35,-35],[35,-35],[35,35],[-35,35]])await page.mouse.click(sketch.x+sketch.width/2+dx,sketch.y+sketch.height/2+dy);
  await page.locator('#contour-close-ring').click();assert.equal(await page.locator('#contour-ring option').count(),2);
  await page.locator('[data-param="thickness"]').fill('0.3');await page.locator('[data-param="thickness"]').press('Tab');await page.locator('#contour-finish').click();
  await page.locator('#btn-ctx-sketch').click();assert.equal(await page.locator('[data-param="thickness"]').inputValue(),'0.3');
  await page.setViewportSize({width:390,height:844});await settle();await page.screenshot({path:'test-results/contour-mobile.png'});
  await checkPixels('#contour-canvas','test-results/contour-canvas-mobile.png');
  await page.locator('#contour-cancel').click();await page.locator('#btn-open-schedule').click();await page.screenshot({path:'test-results/schedule-mobile.png'});
  const bounds=await page.locator('.schedule-dialog').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=391);
  await page.locator('#sched-close').click();await page.setViewportSize({width:1440,height:1000});
  await page.locator('#project-analysis').click();await page.locator('#analysis-tolerance').fill('0.001');page.once('dialog',dialog=>dialog.accept());await page.locator('#analysis-generate').click();await page.locator('#analysis-bases').click();await page.locator('#analysis-solve').click();
  await page.waitForFunction(()=>document.querySelector('#analysis-status')?.textContent.includes('Equilibrio relativo'));
  console.log('Analysis status:',await page.locator('#analysis-status').textContent());
  await page.screenshot({path:'test-results/analysis-desktop.png'});
  const reportWait=page.waitForEvent('download');await page.locator('#analysis-report').click();await (await reportWait).saveAs('test-results/memoria.html');
  const reportPage=await context.newPage();await reportPage.goto(pathToFileURL(resolve('test-results/memoria.html')).href);
  assert.ok(await reportPage.locator('img').evaluate(img=>img.complete&&img.naturalWidth>0));
  await reportPage.screenshot({path:'test-results/memoria.png',fullPage:true});await reportPage.close();
  await page.locator('#analysis-close').click();
  await page.waitForFunction(()=>document.querySelector('#project-save-status')?.textContent==='Guardado local');
  const saveWait=page.waitForEvent('download');await page.locator('#project-save').click();await (await saveWait).saveAs('test-results/project.arm.json');
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#project-save-status')?.textContent==='Proyecto recuperado');
  await page.locator('#project-analysis').click();assert.ok(await page.locator('[data-support]').count()>0);await page.locator('#analysis-close').click();
  const original=JSON.parse(await readFile('test-results/project.arm.json','utf8'));
  const recoveredWait=page.waitForEvent('download');await page.locator('#project-save').click();await (await recoveredWait).saveAs('test-results/recovered.arm.json');
  const recovered=JSON.parse(await readFile('test-results/recovered.arm.json','utf8'));
  assert.deepEqual(recovered.elements.map(e=>[e.uniqueId,e.typeId,e.familyType,e.geometry.definition]),original.elements.map(e=>[e.uniqueId,e.typeId,e.familyType,e.geometry.definition]));
  assert.deepEqual(recovered.analysis.model.nodes,original.analysis.model.nodes);
  page.once('dialog',dialog=>dialog.accept());await page.locator('#project-file').setInputFiles('test-results/project.arm.json');
  await page.waitForFunction(()=>document.querySelector('#project-save-status')?.textContent==='Guardado local');
  await page.locator('#project-analysis').click();assert.ok(await page.locator('[data-support]').count()>0);
  await page.locator('#analysis-solve').click();await page.waitForFunction(()=>document.querySelector('#analysis-status')?.textContent.includes('Equilibrio relativo'));
  assert.equal(await page.locator('#analysis-solve').isEnabled(),true);
  await page.locator('#analysis-tolerance').fill('0.5');await page.locator('#analysis-tolerance').press('Tab');
  assert.equal(await page.locator('#analysis-report').isEnabled(),false);assert.equal(await page.locator('#analysis-solve').isEnabled(),false);
  await page.locator('#analysis-close').click();
  await page.locator('#btn-open-schedule').click();assert.ok(await page.locator('#sched-body tr[data-index]').count()>0);
  assert.deepEqual(errors,[]);console.log('Browser smoke passed');
}finally{await browser.close();}
