import type {LoadLedger} from '../core/analysis/LoadLedger';
import {escapeHtml as h,icon} from './shared';

export type LoadFilter='applied'|'pending'|'all';
const f=(v:number|null)=>v===null?'Pendiente':v.toFixed(3);
const labels={applied:'En portico', 'outside-plane':'Fuera del plano','transfer-pending':'Sin transferencia BIM','transfer-linked':'Fuente superficial declarada',unsupported:'Fuera del motor','missing-source':'Sin fuente BIM'};

export function loadBalanceView(ledger:LoadLedger,filter:LoadFilter):string {
  const totals=ledger.assembled.totals,eq=ledger.equilibrium;
  const rows=ledger.rows.filter(r=>filter==='all'||(filter==='applied'?r.memberIds.length>0||r.status==='transfer-linked':r.memberIds.length===0&&r.status!=='transfer-linked'));
  const pending=ledger.rows.filter(r=>r.status==='transfer-pending').length;
  return `<div class="load-balance-summary">
    <div><span>PP automatico activo</span><strong>${f(totals.selfWeight)} kN</strong><small>Excluido por D total: ${f(totals.excludedSelfWeight)} kN</small></div>
    <div><span>D manual sin factor</span><strong>${f(totals.manualDead)} kN</strong><small>L manual: ${f(totals.manualLive)} kN</small><small>D / L superficial: ${f(totals.surfaceDead)} / ${f(totals.surfaceLive)} kN</small></div>
    <div><span>Fy aplicado / caso</span><strong id="load-balance-fy">${f(totals.fy)} kN</strong><small>Fx: ${f(totals.fx)} kN / M horario: ${f(totals.moment)} kN m</small></div>
    <div><span>Reacciones del caso</span><strong>${eq?f(eq.reactionY)+' kN':'Sin resultado vigente'}</strong><small>${eq?'Ry + Fy: '+(eq.reactionY+totals.fy).toExponential(3)+' kN':'Balance previo al calculo'}</small></div>
  </div>
  <div class="load-balance-warning">${pending} losas sin transferencia BIM vinculada. El volumen neto es comparativo: no modifica cargas. Las entradas manuales no acreditan E.020.</div>
  ${ledger.loadValidationError?`<div class="load-balance-warning" role="status">Calculo bloqueado: ${h(ledger.loadValidationError)}</div>`:''}
  ${surfaceBalanceView(ledger)}
  <div class="load-balance-tools"><label>Fuentes<select id="load-balance-filter"><option value="applied" ${filter==='applied'?'selected':''}>En el portico</option><option value="pending" ${filter==='pending'?'selected':''}>Fuera del calculo</option><option value="all" ${filter==='all'?'selected':''}>Todas</option></select></label><span>Plano ${h(ledger.plane)} / ${ledger.ordinate} m / ${rows.length} fuentes / revision ${ledger.modelRevision}</span><div class="workspace-actions"><button id="load-balance-csv" title="Exportar balance completo CSV">${icon('Download')} CSV</button><button id="load-balance-json" title="Exportar fuentes y tramos JSON">${icon('Download')} JSON</button></div></div>
  <div class="load-balance-table"><table class="schedule-table"><thead><tr><th>Elemento / nivel BIM</th><th>Estado / tramos</th><th>L FEM (m)</th><th>V bruto / neto (m3)</th><th>Peso unitario (kN/m3)</th><th>PP activo / excluido (kN)</th><th>D / L manual (kN)</th><th>Referencia peso bruto / neto (kN)</th><th>Carga del caso hacia abajo (kN)</th><th>Observaciones</th></tr></thead><tbody>${rows.map(r=>`<tr data-load-source="${h(r.sourceId)}"><td><button data-focus="${h(r.sourceId)}" title="${h(r.sourceId)}">${h(r.mark)}</button><small>${h(r.level)} / ${h(r.material)}</small></td><td>${labels[r.status]}<small>${h(r.memberIds.join(', ')||'Sin tramos')}</small></td><td>${f(r.length)}</td><td>${f(r.grossVolume)} / ${f(r.netVolume)}</td><td>${f(r.unitWeight)}</td><td>${f(r.selfWeight)} / ${f(r.excludedSelfWeight)}</td><td>${f(r.manualDead)} / ${f(r.manualLive)}</td><td>${f(r.grossReferenceWeight)} / ${f(r.netReferenceWeight)}</td><td>${f(r.downward)}</td><td class="load-note">${h(r.notes.join(' ')||'Peso de barras bruto. Sin verificacion normativa.')}</td></tr>`).join('')}</tbody></table></div>
  <details class="load-balance-details"><summary>Totales por nivel BIM de origen</summary><table class="schedule-table"><thead><tr><th>Nivel</th><th>PP activo (kN)</th><th>D manual (kN)</th><th>L manual (kN)</th><th>Caso descendente (kN)</th><th>Losas pendientes</th></tr></thead><tbody>${ledger.levels.map(l=>`<tr><td>${h(l.level)}</td><td>${f(l.selfWeight)}</td><td>${f(l.manualDead)}</td><td>${f(l.manualLive)}</td><td>${f(l.downward)}</td><td>${l.pending}</td></tr>`).join('')}</tbody></table></details>
  <details class="load-balance-details"><summary>Cargas nodales aplicadas (no incluidas en los totales por nivel)</summary><table class="schedule-table"><thead><tr><th>Nudo</th><th>Fx (kN)</th><th>Fy (kN)</th><th>M horario (kN m)</th></tr></thead><tbody>${ledger.assembled.nodes.filter(n=>n.fx||n.fy||n.moment).map(n=>`<tr><td>${h(n.id)}</td><td>${f(n.fx)}</td><td>${f(n.fy)}</td><td>${f(n.moment)}</td></tr>`).join('')}</tbody></table></details>`;
}

function surfaceBalanceView(ledger:LoadLedger):string {
  if(!ledger.assembled.surfaces.length)return '';
  return `<details class="load-balance-details" open><summary>Reparto superficial declarado / D y L sin factor</summary><table class="schedule-table"><thead><tr><th>Losa</th><th>Fuente D / L (kN)</th><th>Al portico (kN)</th><th>Fuera (kN)</th><th>Pendiente (kN / %)</th><th>Sustento</th></tr></thead><tbody>${ledger.assembled.surfaces.map(s=>`<tr><td>${h(ledger.rows.find(r=>r.sourceId===s.sourceId)?.mark??s.sourceId)}</td><td>${f(s.dead)} / ${f(s.live)}</td><td>${f(s.assignedDead)} / ${f(s.assignedLive)}</td><td>${f(s.outsideDead)} / ${f(s.outsideLive)}</td><td>${f(s.pendingDead)} / ${f(s.pendingLive)} / ${f(s.pendingFraction*100)}%</td><td>${h(s.reference||'Pendiente')} / ${h(s.outsideReference)}</td></tr>`).join('')}</tbody></table><table class="schedule-table"><thead><tr><th>Losa / receptor</th><th>Tramos</th><th>Fraccion (%)</th><th>D / L (kN)</th><th>q D / L (kN/m)</th></tr></thead><tbody>${ledger.assembled.surfaces.flatMap(s=>s.allocations.map(a=>`<tr><td>${h(ledger.rows.find(r=>r.sourceId===s.sourceId)?.mark??s.sourceId)} / ${h(ledger.rows.find(r=>r.sourceId===a.receiverId)?.mark??a.receiverId)}</td><td>${h(a.memberIds.join(', '))}</td><td>${f(a.fraction*100)}</td><td>${f(a.dead)} / ${f(a.live)}</td><td>${f(a.qDead)} / ${f(a.qLive)}</td></tr>`)).join('')}</tbody></table></details>`;
}
