/**
 * Centralized dimensions, tolerances, radii, and metrics configuration (Single Source of Truth).
 * Strict TypeScript definition with immutable constants.
 */

export const DIMENSIONS = {
  grid: {
    yOffsets: {
      base: 0.05,
      glow: -0.005,
      hitbox: 0.03,
      bubble: 0.02,
      bubbleHit: 0.04,
      toggleIcon: 0.07,
      elbowGrip: 0.08,
      grip: 0.06,
      gripHit: 0.07,
      lock: 0.07,
      toggle: 0.07,
      alignmentGuide: 0.08,
      guideLine: 0.06,
    },
    bubbleRadius: 1.2,
    bubbleCanvasSize: 128,
    bubbleStrokeWidthDefault: 6,
    bubbleStrokeWidthHighlighted: 7,
    bubbleStrokeWidthHovered: 8,
    bubbleFontSize: 54,
    bubbleTextOffsetY: 3,
    bubbleSpriteScale: { x: 2.4, y: 2.4, z: 1 },
    bubbleOffset: 1.8,
    bubbleHitRadius: 2.2,
    bubbleDoubleClickMaxDist: 4.0,
    lineWidthSelected: 2.5,
    lineWidthHovered: 2.0,
    lineWidthDefault: 1.5,
    hitboxWidth: 2.2,
    hitboxLengthPadding: 0.5,
    glowWidth: 0.45,
    toggleHitSize: 1.2,
    gripHitRadius: 0.9,
    gripInnerRadius: 0.18,
    gripOuterRadius: 0.36,
    gripSegments: 24,
    lockOffset: 0.7,
    checkboxDirOffset: 0.9,
    checkboxPerpOffset: 0.65,
    arcSegments: 64,
    minSegmentLength: 1.0,
    orthoTolerance: 0.2,
    alignmentAngleTolerance: 0.2,
    alignmentPosTolerance: 0.4,
    alignmentGuideMargin: 4.0,
    alignmentDashSize: 2.8,
    alignmentGapSize: 0.2,
    guideLineExtent: 25,
    guideDashSize: 2.5,
    guideGapSize: 0.25,
    defaultGridSpan: 16.0,
    dashSize: 0.6,
    gapSize: 0.3,
    elbowLeaderDashSize: 0.3,
    elbowLeaderGapSize: 0.2,
    lineWidth: 1,
    controls: {
      checkbox: {
        offset: 1.8,
        spriteScale: { x: 0.7, y: 0.7, z: 1 },
        canvasSize: 64,
        rectX: 8,
        rectY: 8,
        rectWidth: 48,
        rectHeight: 48,
        rectRadius: 6,
        strokeWidth: 4,
        checkStrokeWidth: 6,
      },
      elbow: {
        offset: 2.2,
        spriteScale: { x: 0.8, y: 0.8, z: 1 },
        canvasSize: 64,
        circleRadiusPadding: 4,
        borderWidth: 3,
        glyphLineWidth: 5,
        defaultLateralOffset: -2.5,
        breakFactor: 0.4,
        maxBreakDistance: 4.0,
        minClampedOffset: -12.0,
        maxClampedOffset: 12.0,
        lateralThreshold: 0.4,
        minFallbackOffset: 0.5,
      },
      lock: {
        offset: 3.2,
        spriteScale: { x: 0.65, y: 0.65, z: 1 },
        canvasSize: 48,
        fontSize: 28,
      },
      grips: {
        mainRadius: 0.28,
        elbowRadius: 0.22,
        radialSegments: 16,
      },
      editor: {
        width: 56,
        height: 56,
        borderRadius: '50%',
        fontSize: 22,
        borderWidth: 3,
        maxLength: 5,
        zIndex: 9999,
      },
    },
  },
  levels: {
    boundsExtentDefault: 20,
    dashSize: 0.8,
    gapSize: 0.4,
    opacityLine: 0.55,
    opacityPlane: 0.03,
    headCanvasWidth: 256,
    headCanvasHeight: 96,
    headBubbleRadius: 24,
    headBubbleX: 36,
    headBubbleY: 48,
    headLineWidth: 2.5,
    headLeaderLineWidth: 2,
    headTitleFontSize: 20,
    headElevationFontSize: 17,
    headSpriteScale: { x: 4.8, y: 1.8, z: 1 },
    headOffset: 2.5,
  },
  drawing: {
    previewDashSize: 0.6,
    previewGapSize: 0.3,
    previewLineWidth: 2,
    refDashSize: 0.3,
    refGapSize: 0.3,
    refOpacity: 0.6,
    arcDashSize: 0.5,
    arcGapSize: 0.25,
    arcLineWidth: 2,
    arcCurveSegments: 48,
    pickLinesThreshold: 4.0,
    dimensionCanvasWidth: 256,
    dimensionCanvasHeight: 64,
    dimensionBoxRadius: 8,
    dimensionLineWidth: 2,
    dimensionFontSize: 20,
    dimensionSpriteScale: { x: 3.2, y: 0.8, z: 1 },
  },
  snapping: {
    ringInnerRadius: 0.5,
    ringOuterRadius: 0.8,
    ringSegments: 32,
    snapDistanceThreshold: 2.5,
    ringHeightOffset: 0.05,
  },
  renderOrders: {
    footing: 0,
    column: 1,
    beam: 2,
    slab: 3,
    edgesOffset: 0.1,
    gridHitbox: 899,
    gridLine: 900,
    gridLeaderLine: 905,
    gridAlignmentLine: 910,
    gridBubble: 950,
    gridCheckbox: 960,
    gridLock: 960,
    gridElbowIcon: 965,
    gridControls: 925,
    gridGrips: 930,
    levelSystemDatum: 990,
    placementMesh: 998,
    placementEdges: 999,
    selectionHover: 998,
    selectionBox: 999,
    drawingDimension: 999,
  },
} as const;

export type DimensionsConfig = typeof DIMENSIONS;
